channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.2
- pip:
  - mlflow==2.16.1
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.11.4
name: mlflow-env
